name: ronin
title: Ronin
base: core20
version: "2.0.5"
summary: A Ruby toolkit for security research and development.
description: |
  Ronin is a free and Open Source Ruby toolkit for security research and
  development. Ronin contains many different CLI commands and Ruby libraries for
  a variety of security tasks, such as encoding/decoding data, filter
  IPs/hosts/URLs, querying ASNs, querying DNS, HTTP, scanning for web
  vulnerabilities, spidering websites, install 3rd party repositories of
  exploits and/or payloads, run exploits, generating new exploits, managing
  local databases, fuzzing data, and much more.
license: GPL-3.0+
website: https://ronin-rb.dev
source-code: https://github.com/ronin-rb/snap
issues: https://github.com/ronin-rb/snap/issues

grade: devel
confinement: devmode

parts:
  ronin:
    source: .
    plugin: nil
    build-snaps: [ruby]
    build-packages:
      - gcc
      - g++
      - make
      - libreadline-dev
      - libsqlite3-dev
    override-build: |
      mkdir "${SNAPCRAFT_PART_INSTALL}/bin"
      gem install --bindir "${SNAPCRAFT_PART_INSTALL}/bin" ronin -v "$SNAPCRAFT_PROJECT_VERSION"

apps:
  ronin:
    command: bin/ronin
    adapter: none
    plugs: [home, network, network-bind, removable-media]
  ronin-db:
    command: bin/ronin-db
    adapter: none
    plugs: [home, network, removable-media]
  ronin-exploits:
    command: bin/ronin-exploits
    adapter: none
    plugs: [home, network, network-bind, removable-media]
  ronin-fuzzer:
    command: bin/ronin-fuzzer
    adapter: none
    plugs: [home, network, network-bind, removable-media]
  ronin-payloads:
    command: bin/ronin-payloads
    adapter: none
    plugs: [home, network, network-bind, removable-media]
  ronin-repos:
    command: bin/ronin-repos
    adapter: none
    plugs: [home, network, removable-media]
  ronin-vulns:
    command: bin/ronin-vulns
    adapter: none
    plugs: [home, network, network-bind, removable-media]
  wordlist:
    command: bin/wordlist
    adapter: none
    plugs: [home, network, network-bind, removable-media]
