name: ronin
base: core20
version: "2.0.5"
summary: A Ruby platform for vulnerability research and exploit development.
description: |
  Ronin is a Ruby platform for vulnerability research and exploit development.
  Ronin allows for the rapid development and distribution of code, Exploits
  Payloads, Scanners, etc, via Repositories.
license: GPL-3.0+

grade: devel
confinement: devmode

parts:
  ronin:
    source: .
    plugin: nil
    build-snaps: [ruby]
    build-packages:
      - gcc
      - g++
      - make
      - libreadline-dev
      - libsqlite3-dev
    override-build: |
      mkdir "${SNAPCRAFT_PART_INSTALL}/bin"
      gem install --bindir "${SNAPCRAFT_PART_INSTALL}/bin" ronin -v "$SNAPCRAFT_PROJECT_VERSION"

apps:
  ronin:
    command: bin/ronin
    adapter: none
  ronin-db:
    command: bin/ronin-db
    adapter: none
  ronin-exploits:
    command: bin/ronin-exploits
    adapter: none
  ronin-fuzzer:
    command: bin/ronin-fuzzer
    adapter: none
  ronin-payloads:
    command: bin/ronin-payloads
    adapter: none
  ronin-repos:
    command: bin/ronin-repos
    adapter: none
  ronin-vulns:
    command: bin/ronin-vulns
    adapter: none
  wordlist:
    command: bin/wordlist
    adapter: none
