name: ronin
title: Ronin
base: core22
version: "2.0.5"
summary: A Ruby toolkit for security research and development.
description: |
  Ronin is a free and Open Source Ruby toolkit for security research and
  development. Ronin contains many different CLI commands and Ruby libraries for
  a variety of security tasks, such as encoding/decoding data, filter
  IPs/hosts/URLs, querying ASNs, querying DNS, HTTP, scanning for web
  vulnerabilities, spidering websites, install 3rd party repositories of
  exploits and/or payloads, run exploits, generating new exploits, managing
  local databases, fuzzing data, and much more.
license: GPL-3.0+
website: https://ronin-rb.dev
source-code: https://github.com/ronin-rb/snap
issues: https://github.com/ronin-rb/snap/issues
donation: https://github.com/sponsors/ronin-rb
icon: snap/gui/ronin.svg

grade: devel
confinement: strict

architectures:
  - build-on: [amd64]
    build-for: [amd64]

parts:
  ronin:
    source: .
    plugin: nil
    build-packages:
      - ruby
      - ruby-dev
      - rubygems
      - gcc
      - g++
      - make
      - libreadline-dev
      - libsqlite3-dev
    stage-packages:
      - ruby
      - libruby
      - rubygems
      - libreadline-dev
      - libsqlite3-dev
      - man-db
      - git
      - zip
    override-build: |
      gem install ronin -v "$SNAPCRAFT_PROJECT_VERSION"
      mkdir -p "$SNAPCRAFT_PART_INSTALL/var/lib/gems/3.0.0/"
      cp -R /var/lib/gems/3.0.0/* "$SNAPCRAFT_PART_INSTALL/var/lib/gems/3.0.0/"
      cp /usr/local/bin/{ronin,ronin-db,ronin-exploits,ronin-fuzzer,ronin-payloads,ronin-repos,ronin-vulns,wordlist} "$SNAPCRAFT_PART_INSTALL/usr/bin/"

apps:
  ronin:
    plugs: [home, network, network-bind, removable-media]
    command: usr/bin/ruby $SNAP/usr/bin/ronin
    environment: &appenv
      HOME: $SNAP_REAL_HOME
      # ruby env variables
      RUBYLIB: "${SNAP}/usr/lib/ruby/vendor_ruby/3.0.0:${SNAP}/usr/lib/x86_64-linux-gnu/ruby/vendor_ruby/3.0.0:${SNAP}/usr/lib/ruby/vendor_ruby:${SNAP}/usr/lib/ruby/3.0.0:${SNAP}/usr/lib/x86_64-linux-gnu/ruby/3.0.0"
      GEM_HOME: "${SNAP}/var/lib/gems/3.0.0"
      GEM_PATH: "${SNAP}/usr/lib/ruby/gems/3.0.0:${SNAP}/usr/share/rubygems-integration/all:${SNAP}/var/lib/gems/3.0.0"
      # man env variables
      LD_LIBRARY_PATH: "${SNAP}/lib:${SNAP}/usr/lib:${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}:${SNAP}/usr/lib/man-db"
      MAN_TEST_DISABLE_SYSTEM_CONFIG: 1
      MANPATH: "${SNAP}/usr/share/man"
      GROFF_FONT_PATH: "${SNAP}/usr/share/groff/current/font"
      GROFF_TMAC_PATH: "${SNAP}/usr/share/groff/current/tmac"
      # git env variables
      GIT_EXEC_PATH: "${SNAP}/usr/lib/git-core"
      GIT_TEMPLATE_DIR: "${SNAP}/usr/share/git-core/templates"
      GIT_CONFIG_NOSYSTEM: 1
  ronin-db:
    plugs: [home, network, removable-media]
    command: usr/bin/ruby $SNAP/usr/bin/ronin-db
    environment:
      <<: *appenv
  ronin-exploits:
    plugs: [home, network, network-bind, removable-media]
    command: usr/bin/ruby $SNAP/usr/bin/ronin-exploits
    environment:
      <<: *appenv
  ronin-fuzzer:
    plugs: [home, network, network-bind, removable-media]
    command: usr/bin/ruby $SNAP/usr/bin/ronin-fuzzer
    environment:
      <<: *appenv
  ronin-payloads:
    plugs: [home, network, network-bind, removable-media]
    command: usr/bin/ruby $SNAP/usr/bin/ronin-payloads
    environment:
      <<: *appenv
  ronin-repos:
    plugs: [home, network, removable-media]
    command: usr/bin/ruby $SNAP/usr/bin/ronin-repos
    environment:
      <<: *appenv
  ronin-vulns:
    plugs: [home, network, removable-media]
    command: usr/bin/ruby $SNAP/usr/bin/ronin-vulns
    environment:
      <<: *appenv
  wordlist:
    plugs: [home, network, removable-media]
    command: usr/bin/ruby $SNAP/usr/bin/wordlist
    environment:
      <<: *appenv
