name: ronin
title: Ronin
base: core22
version: "2.0.5"
summary: A Ruby toolkit for security research and development.
description: |
  Ronin is a free and Open Source Ruby toolkit for security research and
  development. Ronin contains many different CLI commands and Ruby libraries for
  a variety of security tasks, such as encoding/decoding data, filter
  IPs/hosts/URLs, querying ASNs, querying DNS, HTTP, scanning for web
  vulnerabilities, spidering websites, install 3rd party repositories of
  exploits and/or payloads, run exploits, generating new exploits, managing
  local databases, fuzzing data, and much more.
license: GPL-3.0+
website: https://ronin-rb.dev
source-code: https://github.com/ronin-rb/snap
issues: https://github.com/ronin-rb/snap/issues
donation: https://github.com/sponsors/ronin-rb
icon: snap/gui/ronin.svg

grade: devel
confinement: devmode

parts:
  ronin:
    source: .
    plugin: nil
    build-packages:
      - ruby
      - ruby-dev
      - rubygems
      - gcc
      - g++
      - make
      - libreadline-dev
      - libsqlite3-dev
    stage-packages:
      - ruby
      - libruby
      - rubygems
      - libreadline-dev
      - libsqlite3-dev
    override-build: |
      gem install ronin -v "$SNAPCRAFT_PROJECT_VERSION"
      mkdir -p "$SNAPCRAFT_PART_INSTALL/var/lib/gems/3.0.0/"
      cp -R /var/lib/gems/3.0.0/* "$SNAPCRAFT_PART_INSTALL/var/lib/gems/3.0.0/"
      cp /usr/local/bin/{ronin,ronin-db,ronin-exploits,ronin-fuzzer,ronin-payloads,ronin-repos,ronin-vulns,wordlist} "$SNAPCRAFT_PART_INSTALL/usr/bin/"

apps:
  ronin:
    command: usr/bin/ruby $SNAP/usr/bin/ronin
    plugs: [home, network, network-bind, removable-media]
  ronin-db:
    command: usr/bin/ruby $SNAP/usr/bin/ronin-db
    plugs: [home, network, removable-media]
  ronin-exploits:
    command: usr/bin/ruby $SNAP/usr/bin/ronin-exploits
    plugs: [home, network, network-bind, removable-media]
  ronin-fuzzer:
    command: usr/bin/ruby $SNAP/usr/bin/ronin-fuzzer
    plugs: [home, network, network-bind, removable-media]
  ronin-payloads:
    command: usr/bin/ruby $SNAP/usr/bin/ronin-payloads
    plugs: [home, network, network-bind, removable-media]
  ronin-repos:
    command: usr/bin/ruby $SNAP/usr/bin/ronin-repos
    plugs: [home, network, removable-media]
  ronin-vulns:
    command: usr/bin/ruby $SNAP/usr/bin/ronin-vulns
    plugs: [home, network, removable-media]
  wordlist:
    command: usr/bin/ruby $SNAP/usr/bin/wordlist
    plugs: [home, network, removable-media]
