name: Snapcraft

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: snapcore/action-build@v1
    - run: |
        sudo snap install --dangerous ${{ steps.build-snap.outputs.snap }}
