name: Snapcraft

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      snap-file: ${{ steps.build-snap.outputs.snap }}
    steps:
    - uses: actions/checkout@v4
    - uses: snapcore/action-build@v1
      id: build-snap
    - run: |
        sudo snap install --devmode --dangerous ${{ steps.build-snap.outputs.snap }}
    - uses: actions/upload-artifact@v3
      with:
        name: ronin.snap
        path: ${{ steps.build-snap.outputs.snap }}

  publish:
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: ronin.snap
        path: .
    - uses: snapcore/action-publish@v1
      env:
        SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_TOKEN }}
      with:
        snap: ${{ needs.build.outputs.snap-file }}
        release: ${{ startsWith(github.ref, 'refs/tags/') && 'candidate' || 'edge'}}
